name: 🐛 Bug Report
description: File a bug report for the Next.js TypeScript application
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us reproduce and fix the issue.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How critical is this bug?
      options:
        - Critical (App breaking)
        - High (Major feature broken)
        - Medium (Minor functionality issue)
        - Low (Cosmetic or edge case)
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component/File Affected
      description: Which component or file is experiencing the issue?
      placeholder: "e.g., Article/elements/ImageCarousel.tsx, Navigation/MobileMenu.tsx"
    validations:
      required: true

  - type: dropdown
    id: geometric_theme
    attributes:
      label: Geometric Theme
      description: Which theme(s) exhibit this bug?
      options:
        - default
        - rounded
        - sharp
        - all themes
        - theme-independent
    validations:
      required: true

  - type: dropdown
    id: language_context
    attributes:
      label: Language Context
      description: Which language(s) are affected?
      options:
        - Russian (ru)
        - English (en)
        - French (fr)
        - Polish (pl)
        - All languages
        - Language-independent
    validations:
      required: true

  - type: dropdown
    id: device_type
    attributes:
      label: Device Type
      description: Where does this bug occur?
      options:
        - Desktop only
        - Mobile only
        - Both desktop and mobile
        - Tablet
        - Unknown/All devices
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps
      description: Clear steps to reproduce the bug
      placeholder: |
        1. Navigate to...
        2. Switch theme to...
        3. Click on...
        4. Observe that...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Describe what actually happens..."
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Console errors, screenshots, or other relevant information
      placeholder: "Console errors, browser info, screenshots..."