blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/yourusername/yourrepo/discussions
    about: For questions and general discussion about the project
  - name: 📖 Documentation
    url: https://github.com/yourusername/yourrepo#readme
    about: Check the README for setup and usage information